### ISSUE TITLE
peer routes: cannot add routes to ip6 peers

### ISSUE THREAD

**Issue by wfleurant** [MassMesh/autoygg#1]
for `./internal/shared.go` we should be passing netmask-cidr and interface-name   
to more of the adaptable %%template-cmd-exampes%% in server/client configs.  

`  _, err = exec.Command("ip", "addr", action, IPAddress+"/"+strconv.Itoa(NetMask), "dev", viper.GetString("YggdrasilInterface")).Output()`

**Comment by cure** [comment]
Could you give this change a try, @wfleurant ? Let me know if that resolves this issue.
