### ISSUE TITLE
Default route in VPN configuration can get lost

### ISSUE THREAD

**Issue by stephen304** [MassMesh/autoygg#15]
I think I finally figured out why my gateway needs a reboot every once in a while, the default route in table 42 gets lost at some point. Replacing it immediately fixes the issue. We could periodically check the route, maybe the vpn interface periodically gets refreshed (maybe something mullvad does involving refreshing connections). Or if we can hook into interface down/up events we could see if that fixes it too.

`ip ro add default dev vpn0 table 42`

I'm using v0.2.2

**Comment by cure** [comment]
@stephen304 do you want to check if this branch works around the problem?

**Comment by stephen304** [comment]
Looks good to me, at least with restarting the openvpn service which seems to emulate the issue. One oddity is that pings and traceroutes don't seem to resume, I wonder if that could cause issues with something like streaming video or a call. But this should be pretty infrequent - so probably not a huge concern.

**Comment by cure** [comment]
This is fixed in [release v0.3.1](https://github.com/MassMesh/autoygg/releases/tag/v0.3.1).
