### ISSUE TITLE
autoygg: add default gateway command

### ISSUE THREAD

**Issue by wfleurant** [MassMesh/autoygg#5]
when there is no gateway, this doesn't apply. but when a gateway exists we cant add a default gateway  

used this to fix it during demo  

in file `/etc/config/autoygg`

`option adddefaultgatewaycommand 'ip ro replace default via %%ClientGateway%%'
`

**Comment by cure** [comment]
This was resolved in commit 99f4927c6017d7e7f0b4e5331e09283783146896, which switched autoygg-client to use 'ip ro replace'.
