### ISSUE TITLE
Automate gateway ip rule to use a separate default gateway for mesh traffic

### ISSUE THREAD

**Issue by stephen304** [MassMesh/autoygg#9]
Afaict, in the default configuration, a connection to a vpn will cause peering to go through, as well as system updates.

I've found this setup to work quite well in isolating mesh traffic to a tun interface:

.ovpn: comment out up/down directives
```
dev vpn0
dev-type tun
route-nopull
```

/etc/iproute2/rt_tables
```
42      mesh
```

```
$ sudo ip rule add from 10.42.0.0/16 table mesh
$ ip ro add default dev vpn0 table mesh
```

```
$ iptables -A FORWARD -i vpn0 -j ACCEPT
$ iptables -A FORWARD -o vpn0 -j ACCEPT
$ iptables -t nat -A POSTROUTING -o vpn0 -j MASQUERADE
```

If some of this could be automated, that would vastly simplify setup with a vpn. These steps should work fine applied to the regular wan interface too.

**Comment by cure** [comment]
The iptables changes were merged as part of #8. Support for the `ip rule` and mesh route table was added in commits cee2bba0e7d7fb6ac6e9f412ffe59a29a79a81f7 and e5e5b22f31b7f37b3706ee597760847ce556cf14. Documentation was added to address the OpenVPN config example and the human-friendly mesh route table name. That happened in commit e254448d5123453e7145dbfcdec4344594ac26f0.
